<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <RootNamespace>HarpyEngine.Rendering</RootNamespace>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Engine\Engine.csproj" />
        <ProjectReference Include="..\Engine.Resources\Engine.Resources.csproj" />

        <PackageReference Include="Silk.NET.OpenGL" Version="2.23.0" />
        <PackageReference Include="Silk.NET.Windowing" Version="2.23.0" />
        <PackageReference Include="Silk.NET.Input" Version="2.23.0" />

        <TrimmerRootAssembly Include="Silk.NET.Windowing.Glfw" />
        <TrimmerRootAssembly Include="Silk.NET.Input.Glfw" />
        <TrimmerRootAssembly Include="Silk.NET.OpenGL" />
    </ItemGroup>
</Project>