<Project>
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <LangVersion>latest</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <OutputPath>$(MSBuildThisFileDirectory)bin\$(Configuration)\</OutputPath>
        <RootNamespace>HarpyEngine.$(MSBuildProjectName.Replace('Engine.', ''))</RootNamespace>
    </PropertyGroup>
</Project>